version: '2'

services:
  app:
    build: .
    image: kadai/todolist-ruby:latest
    container_name: todolist-ruby_app
    tty: true
    stdin_open: true
    command: ["/var/www/startup.sh", "db", "docker", "docker"]
    ports:
      - 3000:3000
    volumes:
      - ./src:/var/www/app
    environment:
      RAILS_ENV: development
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: todolist-ruby_db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: todolist_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"